### ISSUE TITLE
Running REAL_TIME_5_MIN in the first interval throws unexpected error

### ISSUE THREAD

**Issue by blakeShalom** [kmax12/gridstatus#174]
At 01:39 ET I was running tests and saw unexpected errors

`>>> import gridstatus
>>> iso = gridstatus.ISONE()
>>> iso.get_lmp("today", market='REAL_TIME_5_MIN')
[]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../gridstatus/gridstatus/lmp_config.py", line 26, in wrapper
    return self._class_method_wrapper(func, bound_args)
  File ".../gridstatus/gridstatus/lmp_config.py", line 61, in _class_method_wrapper
    return func(*instance_args, **instance_kwargs)
  File ".../gridstatus/gridstatus/decorators.py", line 78, in wrapped_f
    df = f(**args_dict)
  File ".../gridstatus/isone.py", line 307, in get_lmp
    data = pd.concat(dfs)
  File ".../grid_env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File ".../grid_env/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/bellingham/projects/gridstatus-blake/grid_env/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate`

We should probably raise a more user friendly exception to catch during testing in the middle of the night or if this were running on a chron every few hours.

**Comment by Saim-naushad** [comment]
I checked this against the current `main` branch and found a related no-data path that still produces an internal exception.

For a historical `REAL_TIME_5_MIN` request, if every interval download fails, `dfs` remains empty and `data_intervals` remains `None`. The historical branch then executes:

```python
data = data_intervals.copy()
```

which raises:

```text
AttributeError: 'NoneType' object has no attribute 'copy'
```

I reproduced this locally by mocking `pd.read_csv` to fail for every interval, so it does not depend on ISO-NE being unavailable at a particular time.

A focused fix could raise `NoDataFoundException` with the requested date/market when no interval data is available, with a regression test covering the all-downloads-failed path. That would be consistent with the no-data behavior used by other ISO implementations in the library.

Would that scope be useful? I would be happy to submit the implementation and tests.

**Comment by WillKoehrsen** [comment]
@Saim-naushad in the scenario you described:

> For a historical REAL_TIME_5_MIN request, if every interval download fails, dfs remains empty and data_intervals remains None. The historical branch then executes:

the code should indeed raise a `NoDataFoundException`. If you would like to open a PR that implements the behavior, that would be much appreciated.

**Comment by WillKoehrsen** [comment]
The actual issue reported here no longer exists so we can close it.
