### ISSUE TITLE
utils._handle_date creates timezone-less pd.Timestamp objects

### ISSUE THREAD

**Issue by jcsalterego** [kmax12/gridstatus#96]
### Description

Given the current `utils._handle_date` code

```python
def _handle_date(date, tz=None):
    if not isinstance(date, pd.Timestamp):
        date = pd.to_datetime(date)

    if tz and date.tzinfo is None:
        date = date.tz_localize(tz)
    return date
```

passing in `today` from a timezone that's on the other side of the date boundary from US timezones may be problematic.

```python
>>> pd.to_datetime('today')
Timestamp('2022-12-16 00:00:00.000000')
>>> pd.to_datetime('today').tzinfo is None
True
# Checking the equivalent in US/Eastern
>>> pd.to_datetime('2022-12-16 00:00:00.00000+0000').tz_convert('US/Eastern')
Timestamp('2022-12-15 19:00:00-0500', tz='US/Eastern')
```

### Solution

I think the solution involves:

* using `pd.Timestamp(date, tz=tz)`
* enforcing `tz` from callers (which should always be `self.default_timezone` from ISO classes), or falling back to `tz=tzlocal()`
* writing a boatload of tests

**Comment by kmax12** [comment]
just adding an example of this issue I came across when running on a machine in different timezone

It's currently 2022-12-27 18:48:00 in the Ercot default timezone, but the time on the machine is '2022-12-28 00:47:53'. the following call fails
```python
gridstatus.Ercot().get_fuel_mix("today")
```
```
Traceback (most recent call last):
  File "/app/update_iso.py", line 469, in <module>
    raise e
  File "/app/update_iso.py", line 463, in <module>
    update_iso(iso)
  File "/app/update_iso.py", line 399, in update_iso
    UpdateFuelMix(iso).run(db)
  File "/app/update_iso.py", line 67, in run
    items = self.get_items(date=date, *args, **kwargs)
  File "/app/update_iso.py", line 87, in get_items
    df = self.iso.get_fuel_mix(date="today")
  File "/root/.cache/pypoetry/virtualenvs/grid-status-9TtSrW0h-py3.10/lib/python3.10/site-packages/gridstatus/ercot.py", line 163, in get_fuel_mix
    pd.DataFrame(r["data"][today_str])
KeyError: '2022-12-28'
```

**Comment by WillKoehrsen** [comment]
This has been addressed.
